set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

set -g mouse on
set -g allow-rename off
set -g automatic-rename off
set -g set-clipboard on

set-window-option -g mode-keys vi

run '~/.tmux/plugins/tpm/tpm'
