#!/usr/bin/env sh

yabai -m config focus_follows_mouse autofocus
yabai -m config layout stack
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0
